name: 'AirCube Zigbee'
packageKey: 'aircube-zigbee'
permissions:
  zigbee: {}
description: 'StuckAtPrototype AirCube air quality monitor (temperature, humidity, eCO2, eTVOC, VOC Level)'
vendorSupportInformation: 'https://github.com/StuckAtPrototype/AirCube'
